# Generated by Django 2.2.1 on 2019-06-04 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewModel',
        ),
    ]
