# Generated by Django 2.2.1 on 2019-06-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название песни')),
                ('artist', models.CharField(max_length=100, verbose_name='Музыкант')),
                ('album', models.CharField(max_length=50, verbose_name='Альбом')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='Жанр')),
                ('lyrics', models.TextField(blank=True, null=True, verbose_name='Текст песни')),
                ('tone', models.CharField(max_length=10, verbose_name='Тональность')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
            },
        ),
    ]
