# Generated by Django 2.2.1 on 2019-06-05 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0003_auto_20190604_0226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersongs',
            options={'verbose_name': 'Песня пользователя', 'verbose_name_plural': 'Песни пользователей'},
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='usersongs',
            unique_together={('playlist', 'song')},
        ),
        migrations.RemoveField(
            model_name='usersongs',
            name='user',
        ),
    ]
