# Generated by Django 2.2.1 on 2019-06-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20190607_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='pages.Song'),
        ),
        migrations.DeleteModel(
            name='UserSongs',
        ),
    ]
