# Generated by Django 2.2.1 on 2019-06-07 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20190607_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
        migrations.CreateModel(
            name='UserSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.Playlist', verbose_name='Плэйлист')),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.Song', verbose_name='Песня')),
            ],
            options={
                'verbose_name': 'Песня пользователя',
                'verbose_name_plural': 'Песни пользователей',
                'unique_together': {('playlist', 'song')},
            },
        ),
    ]
