# Generated by Django 2.2.1 on 2019-06-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_preview',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='youtube_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
